version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    ports:
      - "9090:9090"
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    networks:
      src_server:
      dst_server:

  client:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    networks:
      src_server:


networks:
  src_server:
  dst_server: