version: '3.9'

services:
  resource:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    volumes:
      - .:/opt/app
    networks:
      dst_server:

  server:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    networks:
      src_server:
      dst_server:

  client:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    networks:
      src_server:


networks:
  src_server:
  dst_server: